"""
P123-Inspired Factor Registry for Korean Equity Ranking.

Each factor defines:
- id: unique identifier
- name: display name
- category: value, quality, growth, momentum, risk, liquidity, sentiment, industry_momentum
- subcategory: grouping within category
- description: what the factor measures
- rank_direction: "higher" or "lower" (higher rank = better)
- scope: "universe", "sector", "industry"
- data_source: "price", "dart", "estimates", "short_interest", "derived"
- implementation_status: "real", "proxy", "unavailable"
- point_in_time_safe: True/False
- required_fields: list of DB fields needed
- lookback_days: how many trading days of history needed
- compute_function: string name of the Python function
- missing_value_policy: "exclude", "neutral", "penalize"
- p123_aliases: list of P123-style formula names this maps to
"""

FACTORS = {
    # =========================================================================
    # VALUE (25% default weight)
    # =========================================================================

    # --- Based on Earnings ---
    "pe_ttm_inv": {
        "name": "P/E TTM (inverted)",
        "category": "value",
        "subcategory": "earnings_based",
        "description": "Earnings yield = Net Income TTM / Market Cap",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["net_income", "market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_earnings_yield",
        "missing_value_policy": "exclude",
        "p123_aliases": ["PEExclXorTTM"],
    },
    "ebitda_ev": {
        "name": "EBITDA / EV",
        "category": "value",
        "subcategory": "earnings_based",
        "description": "EBITDA divided by Enterprise Value",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["ebitda", "market_cap", "total_debt", "cash_and_equivalents"],
        "lookback_days": 0,
        "compute_function": "calc_ebitda_ev",
        "missing_value_policy": "exclude",
        "p123_aliases": ["OpIncBDeprTTM / EV"],
    },

    # --- Based on Sales ---
    "price_sales_ttm_inv": {
        "name": "Price/Sales TTM (inverted)",
        "category": "value",
        "subcategory": "sales_based",
        "description": "Sales yield = Revenue TTM / Market Cap",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["revenue", "market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_sales_yield",
        "missing_value_policy": "exclude",
        "p123_aliases": ["Pr2SalesTTM"],
    },
    "ev_sales_ttm_inv": {
        "name": "EV/Sales TTM (inverted)",
        "category": "value",
        "subcategory": "sales_based",
        "description": "Revenue / Enterprise Value",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["revenue", "market_cap", "total_debt", "cash_and_equivalents"],
        "lookback_days": 0,
        "compute_function": "calc_revenue_ev",
        "missing_value_policy": "exclude",
        "p123_aliases": ["EV2SalesTTM"],
    },
    "gross_profit_ev": {
        "name": "Gross Profit / EV",
        "category": "value",
        "subcategory": "sales_based",
        "description": "Gross Profit divided by Enterprise Value",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["gross_profit", "market_cap", "total_debt", "cash_and_equivalents"],
        "lookback_days": 0,
        "compute_function": "calc_gross_profit_ev",
        "missing_value_policy": "exclude",
        "p123_aliases": ["GrossProfitTTM / EV"],
    },

    # --- Based on Free Cash Flow ---
    "fcf_mcap": {
        "name": "FCF / Market Cap",
        "category": "value",
        "subcategory": "fcf_based",
        "description": "Free Cash Flow yield",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["free_cash_flow", "market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_fcf_yield",
        "missing_value_policy": "exclude",
        "p123_aliases": ["NetFCFPSTTM / Price"],
    },
    "ocf_mcap": {
        "name": "Operating CF / Market Cap",
        "category": "value",
        "subcategory": "fcf_based",
        "description": "Operating cash flow yield",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["operating_cash_flow", "market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_ocf_yield",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },
    "ufcf_ev": {
        "name": "Unlevered FCF / EV",
        "category": "value",
        "subcategory": "fcf_based",
        "description": "(OCF - Capex + 0.8 * Interest) / EV",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["operating_cash_flow", "capex", "interest_expense", "market_cap", "total_debt", "cash_and_equivalents"],
        "lookback_days": 0,
        "compute_function": "calc_ufcf_ev",
        "missing_value_policy": "exclude",
        "p123_aliases": ["(OperCashFlTTM - CapExTTM + 0.8 * IntExpTTM) / EV"],
    },

    # --- Based on Assets ---
    "price_book": {
        "name": "Price / Book",
        "category": "value",
        "subcategory": "asset_based",
        "description": "Book-to-Market = Total Equity / Market Cap",
        "rank_direction": "higher",  # inverted: higher book/market = better value
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["total_equity", "market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_book_to_market",
        "missing_value_policy": "exclude",
        "p123_aliases": ["Pr2BookQ"],
    },
    "dividend_yield": {
        "name": "Dividend Yield",
        "category": "value",
        "subcategory": "asset_based",
        "description": "Dividends Paid / Market Cap",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["dividends_paid", "market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_dividend_yield",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },

    # --- Buyback Yield (shareholder return) ---
    "buyback_yield_yoy": {
        "name": "Buyback Yield YoY",
        "category": "value",
        "subcategory": "asset_based",
        "description": ("(prior_shares - current_shares) / current_shares. "
                        "Positive = net share count reduction (buyback / "
                        "treasury retirement)."),
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["shares_outstanding"],
        "lookback_days": 0,
        "compute_function": "calc_buyback_yield_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },

    # =========================================================================
    # QUALITY (30% default weight)
    # =========================================================================

    # --- Margins ---
    "operating_margin_ttm": {
        "name": "Operating Margin TTM",
        "category": "quality",
        "subcategory": "margins",
        "description": "Operating Income / Revenue",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["operating_income", "revenue"],
        "lookback_days": 0,
        "compute_function": "calc_operating_margin",
        "missing_value_policy": "exclude",
        "p123_aliases": ["OpMgn%TTM"],
    },
    "fcf_to_assets": {
        "name": "FCF / Assets",
        "category": "quality",
        "subcategory": "return_on_capital",
        "description": "Free Cash Flow (TTM) / Total Assets — capital efficiency",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["free_cash_flow", "total_assets"],
        "lookback_days": 0,
        "compute_function": "calc_fcf_to_assets",
        "missing_value_policy": "exclude",
        "p123_aliases": ["FCF/Assets"],
    },
    "cash_to_assets": {
        "name": "Cash / Assets",
        "category": "quality",
        "subcategory": "balance_sheet",
        "description": "Cash & equivalents / Total Assets — balance sheet liquidity",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["cash", "total_assets"],
        "lookback_days": 0,
        "compute_function": "calc_cash_to_assets",
        "missing_value_policy": "exclude",
        "p123_aliases": ["Cash/Assets"],
    },
    "gross_margin_ttm": {
        "name": "Gross Margin TTM",
        "category": "quality",
        "subcategory": "margins",
        "description": "Gross Profit / Revenue",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["gross_profit", "revenue"],
        "lookback_days": 0,
        "compute_function": "calc_gross_margin",
        "missing_value_policy": "exclude",
        "p123_aliases": ["GMgn%TTM"],
    },

    # --- Return on Capital ---
    "roe_ttm": {
        "name": "ROE TTM",
        "category": "quality",
        "subcategory": "return_on_capital",
        "description": "Net Income / Total Equity",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["net_income", "total_equity"],
        "lookback_days": 0,
        "compute_function": "calc_roe",
        "missing_value_policy": "exclude",
        "p123_aliases": ["ROE%TTM"],
    },
    "roa_ttm": {
        "name": "ROA TTM",
        "category": "quality",
        "subcategory": "return_on_capital",
        "description": "Net Income / Total Assets",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["net_income", "total_assets"],
        "lookback_days": 0,
        "compute_function": "calc_roa",
        "missing_value_policy": "exclude",
        "p123_aliases": ["ROA%TTM"],
    },
    "gross_profit_assets": {
        "name": "Gross Profit / Assets",
        "category": "quality",
        "subcategory": "return_on_capital",
        "description": "Novy-Marx gross profitability",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["gross_profit", "total_assets"],
        "lookback_days": 0,
        "compute_function": "calc_gross_profit_assets",
        "missing_value_policy": "exclude",
        "p123_aliases": ["GrossProfit%AssetsTTM"],
    },

    # --- Turnover ---
    "asset_turnover_ttm": {
        "name": "Asset Turnover TTM",
        "category": "quality",
        "subcategory": "turnover",
        "description": "Revenue / Total Assets",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["revenue", "total_assets"],
        "lookback_days": 0,
        "compute_function": "calc_asset_turnover",
        "missing_value_policy": "exclude",
        "p123_aliases": ["AstTurnTTM"],
    },

    # --- Finances ---
    "debt_to_equity": {
        "name": "Debt / Equity",
        "category": "quality",
        "subcategory": "finances",
        "description": "Total Debt / Total Equity (lower is better)",
        "rank_direction": "lower",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["total_debt", "total_equity"],
        "lookback_days": 0,
        "compute_function": "calc_debt_to_equity",
        "missing_value_policy": "exclude",
        "p123_aliases": ["DbtTot2CapQ"],
    },
    "interest_coverage_ttm": {
        "name": "Interest Coverage TTM",
        "category": "quality",
        "subcategory": "finances",
        "description": "EBITDA / Interest Expense",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["ebitda", "interest_expense"],
        "lookback_days": 0,
        "compute_function": "calc_interest_coverage",
        "missing_value_policy": "exclude",
        "p123_aliases": ["IntCovTTM"],
    },

    # =========================================================================
    # GROWTH (15% default weight)
    # =========================================================================

    # --- Sales Growth ---
    "sales_growth_yoy": {
        "name": "Sales Growth YoY",
        "category": "growth",
        "subcategory": "sales",
        "description": "Year-over-year revenue growth",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["revenue"],
        "lookback_days": 0,
        "compute_function": "calc_sales_growth_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": ["SalesGr%PYQ", "SalesGr%TTM"],
    },

    # --- Operating Income Growth ---
    "op_income_growth_yoy": {
        "name": "Op Income Growth YoY",
        "category": "growth",
        "subcategory": "operating_income",
        "description": "Year-over-year operating income growth",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["operating_income"],
        "lookback_days": 0,
        "compute_function": "calc_op_income_growth_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": ["OpIncGr%PYQ", "OpIncGr%TTM"],
    },

    # --- EPS Growth ---
    "eps_growth_yoy": {
        "name": "EPS Growth YoY",
        "category": "growth",
        "subcategory": "eps",
        "description": "Year-over-year EPS growth",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["net_income"],
        "lookback_days": 0,
        "compute_function": "calc_eps_growth_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": ["EPSExclXorGr%PYQ", "EPSExclXorGr%TTM"],
    },

    # --- Net Income Growth ---
    "net_income_growth_yoy": {
        "name": "Net Income Growth YoY",
        "category": "growth",
        "subcategory": "eps",
        "description": "Year-over-year net income growth",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["net_income"],
        "lookback_days": 0,
        "compute_function": "calc_net_income_growth_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },

    # --- Operating Cash Flow Growth ---
    "ocf_growth_yoy": {
        "name": "Operating Cash Flow Growth YoY",
        "category": "growth",
        "subcategory": "cash_flow",
        "description": "Year-over-year operating cash flow growth",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["operating_cash_flow"],
        "lookback_days": 0,
        "compute_function": "calc_ocf_growth_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },

    # --- Free Cash Flow Growth ---
    "fcf_growth_yoy": {
        "name": "Free Cash Flow Growth YoY",
        "category": "growth",
        "subcategory": "cash_flow",
        "description": "Year-over-year free cash flow growth",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "dart",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["free_cash_flow"],
        "lookback_days": 0,
        "compute_function": "calc_fcf_growth_yoy",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },

    # =========================================================================
    # MOMENTUM / TECHNICALS (10% default weight)
    # =========================================================================

    "price_change_120d": {
        "name": "Price Change 120d",
        "category": "momentum",
        "subcategory": "price_changes",
        "description": "Close(0) / Close(120) - 1",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 130,
        "compute_function": "calc_price_change",
        "missing_value_policy": "exclude",
        "p123_aliases": ["Close(0) / Close(120)"],
        "params": {"days": 120},
    },
    "price_change_180d": {
        "name": "Price Change 180d",
        "category": "momentum",
        "subcategory": "price_changes",
        "description": "Close(0) / Close(180) - 1",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 190,
        "compute_function": "calc_price_change",
        "missing_value_policy": "exclude",
        "p123_aliases": ["Close(0) / Close(180)"],
        "params": {"days": 180},
    },
    "momentum_3m": {
        "name": "3-Month Return",
        "category": "momentum",
        "subcategory": "quarterly_returns",
        "description": "63-day price return",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 70,
        "compute_function": "calc_price_change",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
        "params": {"days": 63},
    },
    "momentum_6m": {
        "name": "6-Month Return",
        "category": "momentum",
        "subcategory": "quarterly_returns",
        "description": "126-day price return",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 135,
        "compute_function": "calc_price_change",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
        "params": {"days": 126},
    },
    "momentum_12_1": {
        "name": "12-1M Momentum",
        "category": "momentum",
        "subcategory": "quarterly_returns",
        "description": "12-month return skipping most recent month",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 260,
        "compute_function": "calc_momentum_12_1",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },
    "up_down_ratio_20": {
        "name": "Up/Down Ratio 20d",
        "category": "momentum",
        "subcategory": "technical",
        "description": "Ratio of up days to down days over 20 trading days",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 25,
        "compute_function": "calc_up_down_ratio",
        "missing_value_policy": "exclude",
        "p123_aliases": ["UpDownRatio(20,0)"],
        "params": {"days": 20},
    },
    "up_down_ratio_60": {
        "name": "Up/Down Ratio 60d",
        "category": "momentum",
        "subcategory": "technical",
        "description": "Ratio of up days to down days over 60 trading days",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 65,
        "compute_function": "calc_up_down_ratio",
        "missing_value_policy": "exclude",
        "p123_aliases": ["UpDownRatio(60,0)"],
        "params": {"days": 60},
    },
    "up_down_ratio_120": {
        "name": "Up/Down Ratio 120d",
        "category": "momentum",
        "subcategory": "technical",
        "description": "Ratio of up days to down days over 120 trading days",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 130,
        "compute_function": "calc_up_down_ratio",
        "missing_value_policy": "exclude",
        "p123_aliases": ["UpDownRatio(120,0)"],
        "params": {"days": 120},
    },
    "rsi_200": {
        "name": "RSI 200",
        "category": "momentum",
        "subcategory": "technical",
        "description": "Relative Strength Index over 200 days",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 210,
        "compute_function": "calc_rsi",
        "missing_value_policy": "exclude",
        "p123_aliases": ["RSI(200)"],
        "params": {"period": 200},
    },

    # =========================================================================
    # LOW VOLATILITY / RISK (10% default weight)
    # =========================================================================

    "volatility_252d": {
        "name": "252-Day Volatility",
        "category": "risk",
        "subcategory": "price_volatility",
        "description": "Annualized standard deviation of daily returns over 252 days",
        "rank_direction": "lower",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 260,
        "compute_function": "calc_volatility",
        "missing_value_policy": "exclude",
        "p123_aliases": ["PctDev(252,1)"],
        "params": {"window": 252},
    },
    "volatility_60d": {
        "name": "60-Day Volatility",
        "category": "risk",
        "subcategory": "price_volatility",
        "description": "Annualized standard deviation of daily returns over 60 days",
        "rank_direction": "lower",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 65,
        "compute_function": "calc_volatility",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
        "params": {"window": 60},
    },
    "max_drawdown_252d": {
        "name": "Max Drawdown 252d",
        "category": "risk",
        "subcategory": "price_volatility",
        "description": "Maximum drawdown over 252 trading days",
        "rank_direction": "lower",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 260,
        "compute_function": "calc_max_drawdown",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
        "params": {"window": 252},
    },

    # =========================================================================
    # SIZE / LIQUIDITY
    # =========================================================================

    "market_cap": {
        "name": "Market Cap",
        "category": "liquidity",
        "subcategory": "size",
        "description": "Market capitalization",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_market_cap",
        "missing_value_policy": "exclude",
        "p123_aliases": ["MktCap"],
    },
    "log_market_cap": {
        "name": "Log Market Cap",
        "category": "liquidity",
        "subcategory": "size",
        "description": "Natural log of market cap (for size factor)",
        "rank_direction": "lower",  # smaller = better for size premium
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["market_cap"],
        "lookback_days": 0,
        "compute_function": "calc_log_market_cap",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
    },
    "avg_trading_value_60d": {
        "name": "Avg Trading Value 60d",
        "category": "liquidity",
        "subcategory": "liquidity",
        "description": "Average daily trading value over 60 days",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 65,
        "compute_function": "calc_avg_trading_value",
        "missing_value_policy": "exclude",
        "p123_aliases": ["MedianDailyTot(126)"],
        "params": {"days": 60},
    },
    "share_turnover_65d": {
        "name": "Share Turnover 65d",
        "category": "liquidity",
        "subcategory": "liquidity",
        "description": "Median daily volume / shares outstanding over 65 days",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": ["shares_outstanding"],
        "lookback_days": 70,
        "compute_function": "calc_share_turnover",
        "missing_value_policy": "exclude",
        "p123_aliases": ["MedianVol(65) / SharesCur(0)"],
        "params": {"days": 65},
    },
    "volume_increase_13d": {
        "name": "Volume Increase 13d",
        "category": "liquidity",
        "subcategory": "liquidity",
        "description": "Avg volume last 13 days / Avg volume 13-30 days ago",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "price",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 35,
        "compute_function": "calc_volume_increase",
        "missing_value_policy": "exclude",
        "p123_aliases": ["AvgVol(13) / AvgVol(13,30)"],
    },

    # =========================================================================
    # INDUSTRY MOMENTUM
    # =========================================================================

    "industry_momentum_26w": {
        "name": "Industry 26W Momentum",
        "category": "industry_momentum",
        "subcategory": "industry",
        "description": "Average 26-week return of stocks in same industry",
        "rank_direction": "higher",
        "scope": "industry",
        "data_source": "derived",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 135,
        "compute_function": "calc_industry_momentum",
        "missing_value_policy": "exclude",
        "p123_aliases": ['Aggregate("TotalReturn", #subindustry)'],
        "params": {"days": 126},
    },
    "industry_momentum_52w": {
        "name": "Industry 52W Momentum",
        "category": "industry_momentum",
        "subcategory": "industry",
        "description": "Average 52-week return of stocks in same industry",
        "rank_direction": "higher",
        "scope": "industry",
        "data_source": "derived",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 260,
        "compute_function": "calc_industry_momentum",
        "missing_value_policy": "exclude",
        "p123_aliases": [],
        "params": {"days": 252},
    },

    # =========================================================================
    # SENTIMENT (unavailable without estimate provider)
    # =========================================================================

    "eps_revision_fy": {
        "name": "EPS Estimate Revision (FY)",
        "category": "sentiment",
        "subcategory": "estimate_revision",
        "description": "Change in consensus EPS estimate for current FY",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "estimates",
        "implementation_status": "unavailable",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 0,
        "compute_function": None,
        "missing_value_policy": "exclude",
        "p123_aliases": ["CurFYEPSMean", "CurFYEPS4WkAgo"],
    },
    "eps_surprise_q1": {
        "name": "Latest Earnings Surprise",
        "category": "sentiment",
        "subcategory": "surprise",
        "description": "Most recent quarterly EPS surprise vs consensus",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "estimates",
        "implementation_status": "unavailable",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 0,
        "compute_function": None,
        "missing_value_policy": "exclude",
        "p123_aliases": ["Surprise%Q1"],
    },
    "avg_recommendation": {
        "name": "Average Recommendation",
        "category": "sentiment",
        "subcategory": "recommendations",
        "description": "Mean analyst recommendation (1=strong buy, 5=sell)",
        "rank_direction": "lower",
        "scope": "universe",
        "data_source": "estimates",
        "implementation_status": "unavailable",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 0,
        "compute_function": None,
        "missing_value_policy": "exclude",
        "p123_aliases": ["AvgRec"],
    },
    "short_interest_pct": {
        "name": "Short Interest % Shares",
        "category": "sentiment",
        "subcategory": "short_interest",
        "description": "Short balance as % of shares outstanding",
        "rank_direction": "lower",
        "scope": "universe",
        "data_source": "short_interest",
        "implementation_status": "unavailable",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 0,
        "compute_function": "calc_short_interest_pct",
        "missing_value_policy": "exclude",
        "p123_aliases": ["SI%ShsOut"],
    },
    "insider_net_buying_90d": {
        "name": "Insider Net Buying 90d",
        "category": "sentiment",
        "subcategory": "insider",
        "description": "Net insider share-purchase signal (trailing 90 days), "
                       "normalized by shares outstanding. PIT-safe from "
                       "DART filing dates.",
        "rank_direction": "higher",
        "scope": "universe",
        "data_source": "insider",
        "implementation_status": "real",
        "point_in_time_safe": True,
        "required_fields": [],
        "lookback_days": 90,
        "compute_function": "calc_insider_net_buying_90d",
        "missing_value_policy": "exclude",
        "p123_aliases": ["InsiderBuy90d"],
    },
}


def get_implemented_factors():
    """Return only factors with implementation_status != 'unavailable'."""
    return {k: v for k, v in FACTORS.items() if v["implementation_status"] != "unavailable"}


def get_factors_by_category(category):
    """Return factors in a given category."""
    return {k: v for k, v in FACTORS.items() if v["category"] == category}


def get_factor_ids_for_ranking():
    """Return factor IDs that should be used in ranking (implemented only)."""
    return [k for k, v in FACTORS.items() if v["implementation_status"] in ("real", "proxy")]
